version: '3'
services:
  template_php71:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.1.Dockerfile
    container_name: template_php71
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.18
  template_php72:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.2.Dockerfile
    container_name: template_php72
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.17
  template_php73:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.3.Dockerfile
    container_name: template_php73
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.16
  template_php74:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.4.Dockerfile
    container_name: template_php74
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.15
  template_php78:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.8.Dockerfile
    container_name: template_php78
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.14
  portainer:
    image: portainer/portainer
    container_name: ps_infra_manager
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "9696:9000"
      - "8686:8000"
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.10
  mysql: 
    image: mysql:5.7
    container_name: ps_mysql_server
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3737:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - MYSQL_ROOT_HOST=%
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.12
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: ps_phpmyadmin
    restart: always
    ports:
      - "3434:80"
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - PMA_HOST=172.21.0.12
      - PMA_PORT=3306
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.13

networks:
  localinfra-network:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
