version: '3'
services:
  infra_manager:
    image: portainer/portainer
    container_name: infra_manager
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.10
  mysql: 
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=prestashop_dev
      - MYSQL_ROOT_HOST=%
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.12
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    ports:
      - "3023:80"
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=prestashop_dev
      - PMA_HOST=172.21.0.12
      - PMA_PORT=3306
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.13

networks:
  localinfra-network:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
