version: '3'
services:
  model_ps_php74:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.4.Dockerfile
    container_name: model_ps_php74
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    volumes:
        -  ./volumes/shops/model_ps_php74:/var/www/html
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.14
    env_file:
        - ./env/prestashop/common.env
        - ./env/prestashop/1.7.4.env
    ports:
        - "3019:80"
  infra_manager:
    image: portainer/portainer
    container_name: infra_manager
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.10
  mysql: 
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - MYSQL_ROOT_HOST=%
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.12
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    ports:
      - "3023:80"
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - PMA_HOST=172.21.0.12
      - PMA_PORT=3306
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.13

networks:
  localinfra-network:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
