version: '3'
services:
  ps_instance_creator:
    build:
      context: ./
      dockerfile: ./dockerfiles/ps-instance-creator.Dockerfile
    container_name: ps_instance_creator
    stdin_open: true
    tty: true
    restart: always
    environment:
      - PS_INFRA_NETWORK_ID=prestashop_localinfra_localinfra-network
      - PS_INFRA_MOUNT_SOURCE_PATH=${PWD}/volumes/prestashop-instances
      - PS_INFRA_MOUNT_TARGET_PATH=/var/www/html
      - PS_DB_USER=root
      - PS_DB_SERVER=172.21.0.12
      - PS_DB_PASSWD=Mxloak1244xlnw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/ps-instance-creator:/var/www/html
    ports:
      - "3535:80"
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.19
  template_php7.1:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.1.Dockerfile
    container_name: ps_template_php7.1
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.18
  template_php72:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.2.Dockerfile
    container_name: ps_template_php7.2
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.17
  template_php7.3:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.3.Dockerfile
    container_name: ps_template_php7.3
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.16
  template_php7.4:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-7.4.Dockerfile
    container_name: ps_template_php7.4
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.15
  template_php8.0:
    build:
      context: ./
      dockerfile: ./dockerfiles/php-8.0.Dockerfile
    container_name: ps_template_php8.0
    depends_on:
        - mysql
        - phpmyadmin
    stdin_open: true
    tty: true
    restart: always
    networks:
        localinfra-network:
          ipv4_address: 172.21.0.14
  ps_infra_manager:
    image: portainer/portainer
    container_name: ps_infra_manager
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "9696:9000"
      - "8686:8000"
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.10
  mysql: 
    image: mysql:5.7
    container_name: ps_mysql_server
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - MYSQL_ROOT_HOST=%
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.12
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: ps_phpmyadmin
    restart: always
    ports:
      - "3434:80"
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=Mxloak1244xlnw
      - PMA_HOST=172.21.0.12
      - PMA_PORT=3306
    networks:
      localinfra-network:
        ipv4_address: 172.21.0.13

networks:
  localinfra-network:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
